[package]
name = "fafka"
version = "0.1.0"
authors = ["Romain Hamel <romain.hamel@untienots.com>"]
edition = "2018"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
