[package]
name = "fafka"
version = "0.1.0"
authors = ["Romain Hamel <romain.hamel@untienots.com>"]
edition = "2018"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]

[dev-dependencies]
tempfile = "3"
